hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

trainer:
  # gpus: 1  # Deprecated since pytorchlightning 1.7, removed in 2.0. Replaced by the 2 next attributes
  accelerator: 'gpu'
  devices: 1
  max_epochs: 1
  # val_check_interval: 10
  check_val_every_n_epoch: 1

inference:
  predict: true
  checkpoint_path: "../2023-07-04_11-10-05/checkpoint-epoch=00-step=6-val_accuracy=0.5000.ckpt"

model:
  provider_name: "timm"  # choose from ["timm", "torchvision"]
  model_name: "resnet18"
  model_kwargs:
    pretrained: false  # Deprecated in torchvision since 0.13 (replaced by "weights") but used by timm
    num_classes:
    in_chans:
    output_stride:
    global_pool:
  modifiers:
    change_first_convolutional_layer:
     num_input_channels: 4
    change_last_layer:
      num_outputs: 5

optimizer:
  lr: 1e-2
  weight_decay: 0
  momentum: 0.9
  nesterov: true

data:
  dataset_path: "../../../dataset/"  # Relative to hydra.run.dir
  labels_name: "sentinel2_raster_torch_geo.csv"
  train_batch_size: 2
  inference_batch_size: 2
  num_workers: 8
  units: "pixel"
  crs: 4326
