hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

trainer:
  # gpus: 1  # Deprecated since pytorchlightning 1.7, removed in 2.0. Replaced by the 2 next attributes
  accelerator: "gpu"
  devices: 'auto'
  max_epochs: 20
  # val_check_interval: 2
  check_val_every_n_epoch: 1
  # log_every_n_steps: 100

run:
  predict: false
  checkpoint_path:

model:
  positive_weigh_factor: 10.0
  provider_name: "timm" # choose from ["timm", "torchvision"]
  model_name: "resnet18"
  model_kwargs:
    pretrained: true # Deprecated in torchvision since 0.13 (replaced by "weights") but used by timm
  modifiers:
    change_first_convolutional_layer:
      num_input_channels: 6
    change_last_layer:
      num_outputs: 11255

optimizer:
  lr: 0.001
  weight_decay: 0
  momentum: 0.9
  nesterov: true
  metrics:
    multilabel_accuracy:
      # callable: 'Fmetrics.classification.multilabel_accuracy'
      kwargs:
        num_labels: 11255
        # threshold: 0.1
        average: micro
    multilabel_recall:
      callable: 'Fmetrics.classification.multilabel_recall'
      kwargs:
        num_labels: 11255
        # threshold: 0.1
        average: micro
    multilabel_precision:
      callable: 'Fmetrics.classification.multilabel_precision'
      kwargs:
        num_labels: 11255
        # threshold: 0.1
        average: micro
    multilabel_f1-score:
      callable: 'Fmetrics.classification.multilabel_f1_score'
      kwargs:
        num_labels: 11255
        # threshold: 0.1
        average: micro

data:
  root: "dataset/geolifeclef-2024/"
  data_paths:
    train:
      landsat_data_dir:  "${data.root}TimeSeries-Cubes/TimeSeries-Cubes/GLC24-PA-train-landsat_time_series/"
      bioclim_data_dir:  "${data.root}TimeSeries-Cubes/TimeSeries-Cubes/GLC24-PA-train-bioclimatic_monthly/"
      sentinel_data_dir:  "${data.root}PA_Train_SatellitePatches_RGB/pa_train_patches_rgb/"
    test:
      landsat_data_dir:  "${data.root}TimeSeries-Cubes/TimeSeries-Cubes/GLC24-PA-test-landsat_time_series/"
      bioclim_data_dir:  "${data.root}TimeSeries-Cubes/TimeSeries-Cubes/GLC24-PA-test-bioclimatic_monthly/"
      sentinel_data_dir:  "${data.root}PA_Test_SatellitePatches_RGB/pa_test_patches_rgb/"
  metadata_paths:
    train:  "${data.root}GLC24_PA_metadata_train_train-10.0min.csv"
    val:  "${data.root}GLC24_PA_metadata_train_val-10.0min.csv"
    test:  "${data.root}GLC24_PA_metadata_test-10.0min.csv"
  num_classes: 11255
  download_data: True
  train_batch_size: 64
  inference_batch_size: 16
  num_workers: 16

task:
  task: "classification_multilabel" # ['classification_binary', 'classification_multiclass', 'classification_multilabel']

loggers:
  exp_name: "multimodal_resnet18_ensemble"  # Name of your experiment
  log_dir_name: "tensorboard_logs/"  # Name of the logs directory