hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

run:
  predict: true
  checkpoint_path: "outputs/glc24_cnn_multimodal_ensemble_habitat/2024-09-10_01-42-06_multiclass_correct_split/last.ckpt"

data:
  root: "dataset/geolifeclef-2024_habitats/"
  data_paths:
    train:
      landsat_data_dir: "${data.root}TimeSeries-Cubes/TimeSeries-Cubes/GLC24-PA-train-landsat_time_series/"
      bioclim_data_dir: "${data.root}TimeSeries-Cubes/TimeSeries-Cubes/GLC24-PA-train-bioclimatic_monthly/"
      sentinel_data_dir: "${data.root}PA_Train_SatellitePatches_RGB/pa_train_patches_rgb/"
    test:
      landsat_data_dir: "${data.root}TimeSeries-Cubes/TimeSeries-Cubes/GLC24-PA-test-landsat_time_series/"
      bioclim_data_dir: "${data.root}TimeSeries-Cubes/TimeSeries-Cubes/GLC24-PA-test-bioclimatic_monthly/"
      sentinel_data_dir: "${data.root}PA_Test_SatellitePatches_RGB/pa_test_patches_rgb/"
  metadata_paths:
    train:  "${data.root}GLC24_PA_metadata_habitats-lvl3_train_2_split-10.0%_train.csv"
    val:  "${data.root}GLC24_PA_metadata_habitats-lvl3_train_2_split-10.0%_val.csv"
    test:  "${data.root}GLC24_PA_metadata_habitats-lvl3_test.csv"
  num_classes: &num_classes 174
  download_data: True
  train_batch_size: 64
  inference_batch_size: 16
  num_workers: 1

task:
  task: "classification_multiclass" # ['classification_binary', 'classification_multiclass', 'classification_multilabel']

trainer:
  # gpus: 1  # Deprecated since pytorchlightning 1.7, removed in 2.0. Replaced by the 2 next attributes
  accelerator: "gpu"
  devices: "auto"
  max_epochs: 20
  val_check_interval: 75
  check_val_every_n_epoch: 1
  # log_every_n_steps: 100

model:
  provider_name: "malpolon" # choose from ["malpolon", "timm", "torchvision"]
  model_name: "glc24_multimodal_ensemble"
  model_kwargs:
    pretrained: false # Deprecated in torchvision since 0.13 (replaced by "weights") but used by timm
  modifiers:
    change_last_layer:
      num_outputs: *num_classes

optim:
  loss_kwargs:
  optimizer:
    adamw:
      kwargs:
        lr: 0.00025
      scheduler:
        cosine_annealing_lr:
          kwargs:
            T_max: 25
            verbose: True
  metrics:
    multiclass_accuracy:
      # callable: 'Fmetrics.classification.multiclass_accuracy'
      kwargs:
        num_classes: *num_classes
        average: micro
    multiclass_exact_match:
      callable: "Fmetrics.classification.multiclass_exact_match"
      kwargs:
        num_classes: *num_classes
    multiclass_f1-score:
      callable: "Fmetrics.classification.multiclass_f1_score"
      kwargs:
        num_classes: *num_classes
        average: micro

loggers:
  exp_name: "MME_habitats_no-duplicates_multiclass" # Name of your experiment
  log_dir_name: "tensorboard_logs/" # Name of the logs directory
