defaults:
  - cnn_on_rgb_patches_config

inference:
  predict: true
  checkpoint_path: "../2023-08-03_18-52-45/checkpoint-epoch=00-step=244-val_multiclass_accuracy=0.0771.ckpt"

model:
  modifiers:
    change_first_convolutional_layer:
      num_input_channels: 4
      new_conv_layer_init_func:
        _target_: cnn_on_rgb_nir_patches.NewConvolutionalLayerInitFuncStrategy
        strategy: "red_pretraining"
        rescaling: true
    change_last_layer:
      num_outputs: 10

trainer:
  gpus: 1

data:
  dataset_path: "../../../dataset/"  # Relative to hydra.run.dir
  train_batch_size: 32
